spec:
  replicas: 1
  imagePullSecrets: ""

environment: ""

config:
  otel:
    exporterOtlpEndpoint: ""
  connectionStrings:
    postgres: ""
  jwt:
    audience: ""
    authority: ""
    issuer: ""
  auth0:
    domain: ""
    clientId: ""
    clientSecret: ""
  cmsServices:
    imageAssetManagement:
      baseAddress:
