// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tlis.Cms.UserManagement.Infrastructure.Persistence;

#nullable disable

namespace Tlis.Cms.UserManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20230809124635_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cms_user_management")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tlis.Cms.UserManagement.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", "cms_user_management");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd3fbc38-0a5e-49b4-8190-37b41308e00a"),
                            Name = "system-admin"
                        },
                        new
                        {
                            Id = new Guid("ba78b12a-020b-434e-981d-aaee9b0f2bd6"),
                            Name = "technician"
                        },
                        new
                        {
                            Id = new Guid("763e0b4e-742a-44c4-8a08-0b45d2f34b32"),
                            Name = "moderator"
                        });
                });

            modelBuilder.Entity("Tlis.Cms.UserManagement.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<DateOnly>("MemberSinceDate")
                        .HasColumnType("date")
                        .HasColumnName("member_since_date");

                    b.Property<DateOnly?>("MembershipEndedDate")
                        .HasColumnType("date")
                        .HasColumnName("membership_ended_date");

                    b.Property<string>("MembershipEndedReason")
                        .HasColumnType("text")
                        .HasColumnName("membership_ended_reason");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_url");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Firstname", "Lastname", "Nickname")
                        .IsUnique()
                        .HasDatabaseName("ix_user_firstname_lastname_nickname");

                    b.ToTable("user", "cms_user_management");
                });

            modelBuilder.Entity("Tlis.Cms.UserManagement.Domain.Models.UserRoleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("FunctionEndDate")
                        .HasColumnType("date")
                        .HasColumnName("function_end_date");

                    b.Property<DateOnly>("FunctionStartDate")
                        .HasColumnType("date")
                        .HasColumnName("function_start_date");

                    b.Property<Guid>("RoleForeignKey")
                        .HasColumnType("uuid")
                        .HasColumnName("role_foreign_key");

                    b.Property<Guid>("UserForeignKey")
                        .HasColumnType("uuid")
                        .HasColumnName("user_foreign_key");

                    b.HasKey("Id")
                        .HasName("pk_user_role_history");

                    b.HasIndex("RoleForeignKey")
                        .HasDatabaseName("ix_user_role_history_role_foreign_key");

                    b.HasIndex("UserForeignKey")
                        .HasDatabaseName("ix_user_role_history_user_foreign_key");

                    b.ToTable("user_role_history", "cms_user_management");
                });

            modelBuilder.Entity("Tlis.Cms.UserManagement.Domain.Models.UserRoleHistory", b =>
                {
                    b.HasOne("Tlis.Cms.UserManagement.Domain.Models.Role", "Role")
                        .WithMany("UserRoleHistory")
                        .HasForeignKey("RoleForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_history_role_role_id");

                    b.HasOne("Tlis.Cms.UserManagement.Domain.Models.User", "User")
                        .WithMany("RoleHistory")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_history_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tlis.Cms.UserManagement.Domain.Models.Role", b =>
                {
                    b.Navigation("UserRoleHistory");
                });

            modelBuilder.Entity("Tlis.Cms.UserManagement.Domain.Models.User", b =>
                {
                    b.Navigation("RoleHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
